HTMLWidgets.widget({

  name: 'interacCircos',

  type: 'output',

  factory: function(el, width, height) {

    // Define shared variables for this instance

    function objToArray(objectLiteral1,objectLiteral2) {
      var piece1 = Object.keys(objectLiteral1);
      var piece2 = Object.values(objectLiteral1);
      var piece3 = Object.keys(objectLiteral2);
      var piece4 = Object.values(objectLiteral2);
      var result1 = [];
      var result2 = [];
      for (var i = 0; i < piece1.length; i++) {
        result1.push([piece1[i], piece2[i]])
      }
      for (var i = 0; i < piece3.length; i++) {
        result2.push([piece3[i], piece4[i]])
      }
      var result = [result1,result2]
      return result;
    }

    function objToArray2(objectLiteral1,objectLiteral2) {
      var piece1 = Object.keys(objectLiteral1);
      var piece2 = Object.values(objectLiteral1);
      var piece3 = Object.values(objectLiteral2);
      var result = [];
      for (var i = 0; i < piece1.length; i++) {
        result.push({"id":piece1[i], "color":piece3[i],"len":piece2[i]})
      }
      // console.log(result)
      return result;
    }

    return {

      renderValue: function(opts) {
        // Remove previous occurences of plots in the <div> if any
        d3.select("#"+el.id).selectAll("svg").remove()

        var NGCircosGenome = objToArray(opts.genome,opts.genome2);

        // var maxRadius = Math.min(height, width)/2; // Compute maximal radial space

        // Adapt the radii from relative to absolute values
        // for (var i = 0; i < opts.moduleList.length; i++) { // For each track
        //   opts.moduleList[i][1].maxRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].minRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].BgouterRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].BginnerRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].outerRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].innerRadius *= 0.7*maxRadius
        //   opts.moduleList[i][1].x *= 0.7*maxRadius
        //   opts.moduleList[i][1].y *= 0.7*maxRadius
        //   opts.moduleList[i][1].LinkRadius *= 0.7*maxRadius 
        // }

        NGCircos01 = new NGCircos(... opts.moduleList_NGCircos, NGCircosGenome,{
          // Main configuration
          target : el.id,
          svgWidth : width,
          svgHeight : height,
          chrPad : opts.chrPad,
          innerRadius: opts.innerRadius,
          outerRadius: opts.outerRadius,
          svgClassName : opts.svgClassName,
          zoom : opts.zoom, // Allow zoom and translation
          
          compareEvent : opts.compareEvent,
          compareEventGroupGapRate : opts.compareEventGroupGapRate,
          compareEventGroupDistance : opts.compareEventGroupDistance,
          CNVxlink : opts.CNVxlink,
          CNVMouseEvent : opts.CNVMouseEvent,
          CNVMouseClickDisplay : opts.CNVMouseClickDisplay,
          CNVMouseClickColor : opts.CNVMouseClickColor,
          CNVMouseClickArcOpacity : opts.CNVMouseClickArcOpacity,
          CNVMouseClickArcStrokeColor : opts.CNVMouseClickArcStrokeColor,
          CNVMouseClickArcStrokeWidth : opts.CNVMouseClickArcStrokeWidth,
          CNVMouseClickTextFromData : opts.CNVMouseClickTextFromData,
          CNVMouseClickTextOpacity : opts.CNVMouseClickTextOpacity,
          CNVMouseClickTextColor : opts.CNVMouseClickTextColor,
          CNVMouseClickTextSize : opts.CNVMouseClickTextSize,
          CNVMouseClickTextPostionX : opts.CNVMouseClickTextPostionX,
          CNVMouseClickTextPostionY : opts.CNVMouseClickTextPostionY,
          CNVMouseClickTextDrag : opts.CNVMouseClickTextDrag,
          CNVMouseDownDisplay : opts.CNVMouseDownDisplay,
          CNVMouseDownColor : opts.CNVMouseDownColor,
          CNVMouseDownArcOpacity : opts.CNVMouseDownArcOpacity,
          CNVMouseDownArcStrokeColor : opts.CNVMouseDownArcStrokeColor,
          CNVMouseDownArcStrokeWidth : opts.CNVMouseDownArcStrokeWidth,
          CNVMouseEnterDisplay : opts.CNVMouseEnterDisplay,
          CNVMouseEnterColor : opts.CNVMouseEnterColor,
          CNVMouseEnterArcOpacity : opts.CNVMouseEnterArcOpacity,
          CNVMouseEnterArcStrokeColor : opts.CNVMouseEnterArcStrokeColor,
          CNVMouseEnterArcStrokeWidth : opts.CNVMouseEnterArcStrokeWidth,
          CNVMouseLeaveDisplay : opts.CNVMouseLeaveDisplay,
          CNVMouseLeaveColor : opts.CNVMouseLeaveColor,
          CNVMouseLeaveArcOpacity : opts.CNVMouseLeaveArcOpacity,
          CNVMouseLeaveArcStrokeColor : opts.CNVMouseLeaveArcStrokeColor,
          CNVMouseLeaveArcStrokeWidth : opts.CNVMouseLeaveArcStrokeWidth,
          CNVMouseMoveDisplay : opts.CNVMouseMoveDisplay,
          CNVMouseMoveColor : opts.CNVMouseMoveColor,
          CNVMouseMoveArcOpacity : opts.CNVMouseMoveArcOpacity,
          CNVMouseMoveArcStrokeColor : opts.CNVMouseMoveArcStrokeColor,
          CNVMouseMoveArcStrokeWidth : opts.CNVMouseMoveArcStrokeWidth,
          CNVMouseOutDisplay : opts.CNVMouseOutDisplay,
          CNVMouseOutAnimationTime : opts.CNVMouseOutAnimationTime,
          CNVMouseOutColor : opts.CNVMouseOutColor,
          CNVMouseOutArcOpacity : opts.CNVMouseOutArcOpacity,
          CNVMouseOutArcStrokeColor : opts.CNVMouseOutArcStrokeColor,
          CNVMouseOutArcStrokeWidth : opts.CNVMouseOutArcStrokeWidth,
          CNVMouseUpDisplay : opts.CNVMouseUpDisplay,
          CNVMouseUpColor : opts.CNVMouseUpColor,
          CNVMouseUpArcOpacity : opts.CNVMouseUpArcOpacity,
          CNVMouseUpArcStrokeColor : opts.CNVMouseUpArcStrokeColor,
          CNVMouseUpArcStrokeWidth : opts.CNVMouseUpArcStrokeWidth,
          CNVMouseOverDisplay : opts.CNVMouseOverDisplay,
          CNVMouseOverColor : opts.CNVMouseOverColor,
          CNVMouseOverArcOpacity : opts.CNVMouseOverArcOpacity,
          CNVMouseOverArcStrokeColor : opts.CNVMouseOverArcStrokeColor,
          CNVMouseOverArcStrokeWidth : opts.CNVMouseOverArcStrokeWidth,
          CNVMouseOverTooltipsSetting : opts.CNVMouseOverTooltipsSetting,
          CNVMouseOverTooltipsHtml : opts.CNVMouseOverTooltipsHtml,
          CNVMouseOverTooltipsPosition : opts.CNVMouseOverTooltipsPosition,
          CNVMouseOverTooltipsBackgroundColor : opts.CNVMouseOverTooltipsBackgroundColor,
          CNVMouseOverTooltipsBorderStyle : opts.CNVMouseOverTooltipsBorderStyle,
          CNVMouseOverTooltipsBorderWidth : opts.CNVMouseOverTooltipsBorderWidth,
          CNVMouseOverTooltipsPadding : opts.CNVMouseOverTooltipsPadding,
          CNVMouseOverTooltipsBorderRadius : opts.CNVMouseOverTooltipsBorderRadius,
          CNVMouseOverTooltipsOpacity : opts.CNVMouseOverTooltipsOpacity,
          HEATMAPMouseEvent : opts.HEATMAPMouseEvent,
          HEATMAPMouseClickDisplay : opts.HEATMAPMouseClickDisplay,
          HEATMAPMouseClickColor : opts.HEATMAPMouseClickColor,
          HEATMAPMouseClickOpacity : opts.HEATMAPMouseClickOpacity,
          HEATMAPMouseClickStrokeColor : opts.HEATMAPMouseClickStrokeColor,
          HEATMAPMouseClickStrokeWidth : opts.HEATMAPMouseClickStrokeWidth,
          HEATMAPMouseDownDisplay : opts.HEATMAPMouseDownDisplay,
          HEATMAPMouseDownColor : opts.HEATMAPMouseDownColor,
          HEATMAPMouseDownOpacity : opts.HEATMAPMouseDownOpacity,
          HEATMAPMouseDownStrokeColor : opts.HEATMAPMouseDownStrokeColor,
          HEATMAPMouseDownStrokeWidth : opts.HEATMAPMouseDownStrokeWidth,
          HEATMAPMouseEnterDisplay : opts.HEATMAPMouseEnterDisplay,
          HEATMAPMouseEnterColor : opts.HEATMAPMouseEnterColor,
          HEATMAPMouseEnterOpacity : opts.HEATMAPMouseEnterOpacity,
          HEATMAPMouseEnterStrokeColor : opts.HEATMAPMouseEnterStrokeColor,
          HEATMAPMouseEnterStrokeWidth : opts.HEATMAPMouseEnterStrokeWidth,
          HEATMAPMouseLeaveDisplay : opts.HEATMAPMouseLeaveDisplay,
          HEATMAPMouseLeaveColor : opts.HEATMAPMouseLeaveColor,
          HEATMAPMouseLeaveOpacity : opts.HEATMAPMouseLeaveOpacity,
          HEATMAPMouseLeaveStrokeColor : opts.HEATMAPMouseLeaveStrokeColor,
          HEATMAPMouseLeaveStrokeWidth : opts.HEATMAPMouseLeaveStrokeWidth,
          HEATMAPMouseMoveDisplay : opts.HEATMAPMouseMoveDisplay,
          HEATMAPMouseMoveColor : opts.HEATMAPMouseMoveColor,
          HEATMAPMouseMoveOpacity : opts.HEATMAPMouseMoveOpacity,
          HEATMAPMouseMoveStrokeColor : opts.HEATMAPMouseMoveStrokeColor,
          HEATMAPMouseMoveStrokeWidth : opts.HEATMAPMouseMoveStrokeWidth,
          HEATMAPMouseOutDisplay : opts.HEATMAPMouseOutDisplay,
          HEATMAPMouseOutAnimationTime : opts.HEATMAPMouseOutAnimationTime,
          HEATMAPMouseOutColor : opts.HEATMAPMouseOutColor,
          HEATMAPMouseOutOpacity : opts.HEATMAPMouseOutOpacity,
          HEATMAPMouseOutStrokeColor : opts.HEATMAPMouseOutStrokeColor,
          HEATMAPMouseOutStrokeWidth : opts.HEATMAPMouseOutStrokeWidth,
          HEATMAPMouseUpDisplay : opts.HEATMAPMouseUpDisplay,
          HEATMAPMouseUpColor : opts.HEATMAPMouseUpColor,
          HEATMAPMouseUpOpacity : opts.HEATMAPMouseUpOpacity,
          HEATMAPMouseUpStrokeColor : opts.HEATMAPMouseUpStrokeColor,
          HEATMAPMouseUpStrokeWidth : opts.HEATMAPMouseUpStrokeWidth,
          HEATMAPMouseOverDisplay : opts.HEATMAPMouseOverDisplay,
          HEATMAPMouseOverColor : opts.HEATMAPMouseOverColor,
          HEATMAPMouseOverOpacity : opts.HEATMAPMouseOverOpacity,
          HEATMAPMouseOverStrokeColor : opts.HEATMAPMouseOverStrokeColor,
          HEATMAPMouseOverStrokeWidth : opts.HEATMAPMouseOverStrokeWidth,
          HEATMAPMouseOverTooltipsSetting : opts.HEATMAPMouseOverTooltipsSetting,
          HEATMAPMouseOverTooltipsHtml : opts.HEATMAPMouseOverTooltipsHtml,
          HEATMAPMouseOverTooltipsPosition : opts.HEATMAPMouseOverTooltipsPosition,
          HEATMAPMouseOverTooltipsBackgroundColor : opts.HEATMAPMouseOverTooltipsBackgroundColor,
          HEATMAPMouseOverTooltipsBorderStyle : opts.HEATMAPMouseOverTooltipsBorderStyle,
          HEATMAPMouseOverTooltipsBorderWidth : opts.HEATMAPMouseOverTooltipsBorderWidth,
          HEATMAPMouseOverTooltipsPadding : opts.HEATMAPMouseOverTooltipsPadding,
          HEATMAPMouseOverTooltipsBorderRadius : opts.HEATMAPMouseOverTooltipsBorderRadius,
          HEATMAPMouseOverTooltipsOpacity : opts.HEATMAPMouseOverTooltipsOpacity,
          BUBBLExlink : opts.BUBBLExlink,
          BUBBLEMouseEvent : opts.BUBBLEMouseEvent,
          BUBBLEMouseClickDisplay : opts.BUBBLEMouseClickDisplay,
          BUBBLEMouseClickColor : opts.BUBBLEMouseClickColor,
          BUBBLEMouseClickOpacity : opts.BUBBLEMouseClickOpacity,
          BUBBLEMouseClickStrokeColor : opts.BUBBLEMouseClickStrokeColor,
          BUBBLEMouseClickStrokeWidth : opts.BUBBLEMouseClickStrokeWidth,
          BUBBLEMouseDownDisplay : opts.BUBBLEMouseDownDisplay,
          BUBBLEMouseDownColor : opts.BUBBLEMouseDownColor,
          BUBBLEMouseDownOpacity : opts.BUBBLEMouseDownOpacity,
          BUBBLEMouseDownStrokeColor : opts.BUBBLEMouseDownStrokeColor,
          BUBBLEMouseDownStrokeWidth : opts.BUBBLEMouseDownStrokeWidth,
          BUBBLEMouseEnterDisplay : opts.BUBBLEMouseEnterDisplay,
          BUBBLEMouseEnterColor : opts.BUBBLEMouseEnterColor,
          BUBBLEMouseEnterOpacity : opts.BUBBLEMouseEnterOpacity,
          BUBBLEMouseEnterStrokeColor : opts.BUBBLEMouseEnterStrokeColor,
          BUBBLEMouseEnterStrokeWidth : opts.BUBBLEMouseEnterStrokeWidth,
          BUBBLEMouseLeaveDisplay : opts.BUBBLEMouseLeaveDisplay,
          BUBBLEMouseLeaveColor : opts.BUBBLEMouseLeaveColor,
          BUBBLEMouseLeaveOpacity : opts.BUBBLEMouseLeaveOpacity,
          BUBBLEMouseLeaveStrokeColor : opts.BUBBLEMouseLeaveStrokeColor,
          BUBBLEMouseLeaveStrokeWidth : opts.BUBBLEMouseLeaveStrokeWidth,
          BUBBLEMouseMoveDisplay : opts.BUBBLEMouseMoveDisplay,
          BUBBLEMouseMoveColor : opts.BUBBLEMouseMoveColor,
          BUBBLEMouseMoveOpacity : opts.BUBBLEMouseMoveOpacity,
          BUBBLEMouseMoveStrokeColor : opts.BUBBLEMouseMoveStrokeColor,
          BUBBLEMouseMoveStrokeWidth : opts.BUBBLEMouseMoveStrokeWidth,
          BUBBLEMouseOutDisplay : opts.BUBBLEMouseOutDisplay,
          BUBBLEMouseOutAnimationTime : opts.BUBBLEMouseOutAnimationTime,
          BUBBLEMouseOutColor : opts.BUBBLEMouseOutColor,
          BUBBLEMouseOutOpacity : opts.BUBBLEMouseOutOpacity,
          BUBBLEMouseOutStrokeColor : opts.BUBBLEMouseOutStrokeColor,
          BUBBLEMouseOutStrokeWidth : opts.BUBBLEMouseOutStrokeWidth,
          BUBBLEMouseUpDisplay : opts.BUBBLEMouseUpDisplay,
          BUBBLEMouseUpColor : opts.BUBBLEMouseUpColor,
          BUBBLEMouseUpOpacity : opts.BUBBLEMouseUpOpacity,
          BUBBLEMouseUpStrokeColor : opts.BUBBLEMouseUpStrokeColor,
          BUBBLEMouseUpStrokeWidth : opts.BUBBLEMouseUpStrokeWidth,
          BUBBLEMouseOverDisplay : opts.BUBBLEMouseOverDisplay,
          BUBBLEMouseOverColor : opts.BUBBLEMouseOverColor,
          BUBBLEMouseOverOpacity : opts.BUBBLEMouseOverOpacity,
          BUBBLEMouseOverStrokeColor : opts.BUBBLEMouseOverStrokeColor,
          BUBBLEMouseOverStrokeWidth : opts.BUBBLEMouseOverStrokeWidth,
          BUBBLEMouseOverTooltipsSetting : opts.BUBBLEMouseOverTooltipsSetting,
          BUBBLEMouseOverTooltipsHtml : opts.BUBBLEMouseOverTooltipsHtml,
          BUBBLEMouseOverTooltipsPosition : opts.BUBBLEMouseOverTooltipsPosition,
          BUBBLEMouseOverTooltipsBackgroundColor : opts.BUBBLEMouseOverTooltipsBackgroundColor,
          BUBBLEMouseOverTooltipsBorderStyle : opts.BUBBLEMouseOverTooltipsBorderStyle,
          BUBBLEMouseOverTooltipsBorderWidth : opts.BUBBLEMouseOverTooltipsBorderWidth,
          BUBBLEMouseOverTooltipsPadding : opts.BUBBLEMouseOverTooltipsPadding,
          BUBBLEMouseOverTooltipsBorderRadius : opts.BUBBLEMouseOverTooltipsBorderRadius,
          BUBBLEMouseOverTooltipsOpacity : opts.BUBBLEMouseOverTooltipsOpacity,
          SNPxlink : opts.SNPxlink,
          SNPMouseEvent : opts.SNPMouseEvent,
          SNPMouseCombinationEvent : opts.SNPMouseCombinationEvent,
          SNPMouseCombinationImageDisplay : opts.SNPMouseCombinationImageDisplay,
          SNPMouseCombinationImageTitle : opts.SNPMouseCombinationImageTitle,
          SNPMouseCombinationImageTitleSize : opts.SNPMouseCombinationImageTitleSize,
          SNPMouseCombinationImageTitleWeight : opts.SNPMouseCombinationImageTitleWeight,
          SNPMouseCombinationImageTitleColor : opts.SNPMouseCombinationImageTitleColor,
          SNPMouseCombinationImagePositionX : opts.SNPMouseCombinationImagePositionX,
          SNPMouseCombinationImagePositionY : opts.SNPMouseCombinationImagePositionY,
          SNPMouseCombinationImageHeight : opts.SNPMouseCombinationImageHeight,
          SNPMouseCombinationImageWidth : opts.SNPMouseCombinationImageWidth,
          SNPMouseCombinationGraphDisplay : opts.SNPMouseCombinationGraphDisplay,
          SNPMouseCombinationGraphTitle : opts.SNPMouseCombinationGraphTitle,
          SNPMouseCombinationGraphTitleSize : opts.SNPMouseCombinationGraphTitleSize,
          SNPMouseCombinationGraphTitleWeight : opts.SNPMouseCombinationGraphTitleWeight,
          SNPMouseCombinationGraphTitleColor : opts.SNPMouseCombinationGraphTitleColor,
          SNPMouseCombinationGraphType : opts.SNPMouseCombinationGraphType,
          SNPMouseCombinationGraphPositionX : opts.SNPMouseCombinationGraphPositionX,
          SNPMouseCombinationGraphPositionY : opts.SNPMouseCombinationGraphPositionY,
          SNPMouseCombinationGraphHeight : opts.SNPMouseCombinationGraphHeight,
          SNPMouseCombinationGraphWidth : opts.SNPMouseCombinationGraphWidth,
          SNPMouseCombinationGraphHistogramBarColor : opts.SNPMouseCombinationGraphHistogramBarColor,
          SNPMouseCombinationGraphHistogramPadding : opts.SNPMouseCombinationGraphHistogramPadding,
          SNPMouseCombinationGraphHistogramPositionCorrectX : opts.SNPMouseCombinationGraphHistogramPositionCorrectX,
          SNPMouseCombinationGraphPieAutoColor : opts.SNPMouseCombinationGraphPieAutoColor,
          SNPMouseCombinationGraphPieColor : opts.SNPMouseCombinationGraphPieColor,
          SNPMouseCombinationGraphPieSize : opts.SNPMouseCombinationGraphPieSize,
          SNPMouseCombinationGraphPieStroke : opts.SNPMouseCombinationGraphPieStroke,
          SNPMouseCombinationGraphPieStrokeColor : opts.SNPMouseCombinationGraphPieStrokeColor,
          SNPMouseCombinationGraphPieStrokeWidth : opts.SNPMouseCombinationGraphPieStrokeWidth,
          SNPMouseCombinationGraphPieOpacity : opts.SNPMouseCombinationGraphPieOpacity,
          SNPMouseCombinationGraphLineType : opts.SNPMouseCombinationGraphLineType,
          SNPMouseCombinationGraphLineColor : opts.SNPMouseCombinationGraphLineColor,
          SNPMouseCombinationGraphLineWidth : opts.SNPMouseCombinationGraphLineWidth,
          SNPMouseCombinationGraphLinePoint : opts.SNPMouseCombinationGraphLinePoint,
          SNPMouseCombinationGraphLinePointSize : opts.SNPMouseCombinationGraphLinePointSize,
          SNPMouseCombinationGraphLinePointAutoColor : opts.SNPMouseCombinationGraphLinePointAutoColor,
          SNPMouseCombinationGraphLinePointColor : opts.SNPMouseCombinationGraphLinePointColor,
          SNPMouseCombinationGraphLinePointStroke : opts.SNPMouseCombinationGraphLinePointStroke,
          SNPMouseCombinationGraphLinePointStrokeColor : opts.SNPMouseCombinationGraphLinePointStrokeColor,
          SNPMouseCombinationGraphLinePointStrokeWidth : opts.SNPMouseCombinationGraphLinePointStrokeWidth,
          SNPMouseCombinationGraphLinePointOpacity : opts.SNPMouseCombinationGraphLinePointOpacity,
          SNPMouseCombinationGraphLinePositionCorrectX : opts.SNPMouseCombinationGraphLinePositionCorrectX,
          SNPMouseCombinationTextDisplay : opts.SNPMouseCombinationTextDisplay,
          SNPMouseCombinationTextColor : opts.SNPMouseCombinationTextColor,
          SNPMouseCombinationTextSize : opts.SNPMouseCombinationTextSize,
          SNPMouseCombinationTextWeight : opts.SNPMouseCombinationTextWeight,
          SNPMouseCombinationTextPositionCorrectX : opts.SNPMouseCombinationTextPositionCorrectX,
          SNPMouseCombinationTextPositionCorrectY : opts.SNPMouseCombinationTextPositionCorrectY,
          SNPMouseClickDisplay : opts.SNPMouseClickDisplay,
          SNPMouseClickColor : opts.SNPMouseClickColor,
          SNPMouseClickCircleSize : opts.SNPMouseClickCircleSize,
          SNPMouseClickCircleOpacity : opts.SNPMouseClickCircleOpacity,
          SNPMouseClickCircleStrokeColor : opts.SNPMouseClickCircleStrokeColor,
          SNPMouseClickCircleStrokeWidth : opts.SNPMouseClickCircleStrokeWidth,
          SNPMouseClickTextFromData : opts.SNPMouseClickTextFromData,
          SNPMouseClickTextOpacity : opts.SNPMouseClickTextOpacity,
          SNPMouseClickTextColor : opts.SNPMouseClickTextColor,
          SNPMouseClickTextSize : opts.SNPMouseClickTextSize,
          SNPMouseClickTextPostionX : opts.SNPMouseClickTextPostionX,
          SNPMouseClickTextPostionY : opts.SNPMouseClickTextPostionY,
          SNPMouseClickTextDrag : opts.SNPMouseClickTextDrag,
          SNPMouseDownDisplay : opts.SNPMouseDownDisplay,
          SNPMouseDownColor : opts.SNPMouseDownColor,
          SNPMouseDownCircleSize : opts.SNPMouseDownCircleSize,
          SNPMouseDownCircleOpacity : opts.SNPMouseDownCircleOpacity,
          SNPMouseDownCircleStrokeColor : opts.SNPMouseDownCircleStrokeColor,
          SNPMouseDownCircleStrokeWidth : opts.SNPMouseDownCircleStrokeWidth,
          SNPMouseEnterDisplay : opts.SNPMouseEnterDisplay,
          SNPMouseEnterColor : opts.SNPMouseEnterColor,
          SNPMouseEnterCircleSize : opts.SNPMouseEnterCircleSize,
          SNPMouseEnterCircleOpacity : opts.SNPMouseEnterCircleOpacity,
          SNPMouseEnterCircleStrokeColor : opts.SNPMouseEnterCircleStrokeColor,
          SNPMouseEnterCircleStrokeWidth : opts.SNPMouseEnterCircleStrokeWidth,
          SNPMouseLeaveDisplay : opts.SNPMouseLeaveDisplay,
          SNPMouseLeaveColor : opts.SNPMouseLeaveColor,
          SNPMouseLeaveCircleSize : opts.SNPMouseLeaveCircleSize,
          SNPMouseLeaveCircleOpacity : opts.SNPMouseLeaveCircleOpacity,
          SNPMouseLeaveCircleStrokeColor : opts.SNPMouseLeaveCircleStrokeColor,
          SNPMouseLeaveCircleStrokeWidth : opts.SNPMouseLeaveCircleStrokeWidth,
          SNPMouseMoveDisplay : opts.SNPMouseMoveDisplay,
          SNPMouseMoveColor : opts.SNPMouseMoveColor,
          SNPMouseMoveCircleSize : opts.SNPMouseMoveCircleSize,
          SNPMouseMoveCircleOpacity : opts.SNPMouseMoveCircleOpacity,
          SNPMouseMoveCircleStrokeColor : opts.SNPMouseMoveCircleStrokeColor,
          SNPMouseMoveCircleStrokeWidth : opts.SNPMouseMoveCircleStrokeWidth,
          SNPMouseOutDisplay : opts.SNPMouseOutDisplay,
          SNPMouseOutAnimationTime : opts.SNPMouseOutAnimationTime,
          SNPMouseOutColor : opts.SNPMouseOutColor,
          SNPMouseOutCircleSize : opts.SNPMouseOutCircleSize,
          SNPMouseOutCircleOpacity : opts.SNPMouseOutCircleOpacity,
          SNPMouseOutCircleStrokeColor : opts.SNPMouseOutCircleStrokeColor,
          SNPMouseOutCircleStrokeWidth : opts.SNPMouseOutCircleStrokeWidth,
          SNPMouseUpDisplay : opts.SNPMouseUpDisplay,
          SNPMouseUpColor : opts.SNPMouseUpColor,
          SNPMouseUpCircleSize : opts.SNPMouseUpCircleSize,
          SNPMouseUpCircleOpacity : opts.SNPMouseUpCircleOpacity,
          SNPMouseUpCircleStrokeColor : opts.SNPMouseUpCircleStrokeColor,
          SNPMouseUpCircleStrokeWidth : opts.SNPMouseUpCircleStrokeWidth,
          SNPMouseOverDisplay : opts.SNPMouseOverDisplay,
          SNPMouseOverColor : opts.SNPMouseOverColor,
          SNPMouseOverCircleSize : opts.SNPMouseOverCircleSize,
          SNPMouseOverCircleOpacity : opts.SNPMouseOverCircleOpacity,
          SNPMouseOverCircleStrokeColor : opts.SNPMouseOverCircleStrokeColor,
          SNPMouseOverCircleStrokeWidth : opts.SNPMouseOverCircleStrokeWidth,
          SNPMouseOverTooltipsSetting : opts.SNPMouseOverTooltipsSetting,
          SNPMouseOverTooltipsHtml : opts.SNPMouseOverTooltipsHtml,
          SNPMouseOverTooltipsPosition : opts.SNPMouseOverTooltipsPosition,
          SNPMouseOverTooltipsBackgroundColor : opts.SNPMouseOverTooltipsBackgroundColor,
          SNPMouseOverTooltipsBorderStyle : opts.SNPMouseOverTooltipsBorderStyle,
          SNPMouseOverTooltipsBorderWidth : opts.SNPMouseOverTooltipsBorderWidth,
          SNPMouseOverTooltipsPadding : opts.SNPMouseOverTooltipsPadding,
          SNPMouseOverTooltipsBorderRadius : opts.SNPMouseOverTooltipsBorderRadius,
          SNPMouseOverTooltipsOpacity : opts.SNPMouseOverTooltipsOpacity,
          LINKxlink : opts.LINKxlink,
          LINKMouseEvent : opts.LINKMouseEvent,
          LINKMouseClickDisplay : opts.LINKMouseClickDisplay,
          LINKMouseClickOpacity : opts.LINKMouseClickOpacity,
          LINKMouseClickStrokeColor : opts.LINKMouseClickStrokeColor,
          LINKMouseClickStrokeWidth : opts.LINKMouseClickStrokeWidth,
          LINKMouseDownDisplay : opts.LINKMouseDownDisplay,
          LINKMouseDownOpacity : opts.LINKMouseDownOpacity,
          LINKMouseDownStrokeColor : opts.LINKMouseDownStrokeColor,
          LINKMouseDownStrokeWidth : opts.LINKMouseDownStrokeWidth,
          LINKMouseEnterDisplay : opts.LINKMouseEnterDisplay,
          LINKMouseEnterOpacity : opts.LINKMouseEnterOpacity,
          LINKMouseEnterStrokeColor : opts.LINKMouseEnterStrokeColor,
          LINKMouseEnterStrokeWidth : opts.LINKMouseEnterStrokeWidth,
          LINKMouseLeaveDisplay : opts.LINKMouseLeaveDisplay,
          LINKMouseLeaveOpacity : opts.LINKMouseLeaveOpacity,
          LINKMouseLeaveStrokeColor : opts.LINKMouseLeaveStrokeColor,
          LINKMouseLeaveStrokeWidth : opts.LINKMouseLeaveStrokeWidth,
          LINKMouseMoveDisplay : opts.LINKMouseMoveDisplay,
          LINKMouseMoveOpacity : opts.LINKMouseMoveOpacity,
          LINKMouseMoveStrokeColor : opts.LINKMouseMoveStrokeColor,
          LINKMouseMoveStrokeWidth : opts.LINKMouseMoveStrokeWidth,
          LINKMouseOutDisplay : opts.LINKMouseOutDisplay,
          LINKMouseOutAnimationTime : opts.LINKMouseOutAnimationTime,
          LINKMouseOutOpacity : opts.LINKMouseOutOpacity,
          LINKMouseOutStrokeColor : opts.LINKMouseOutStrokeColor,
          LINKMouseOutStrokeWidth : opts.LINKMouseOutStrokeWidth,
          LINKMouseUpDisplay : opts.LINKMouseUpDisplay,
          LINKMouseUpOpacity : opts.LINKMouseUpOpacity,
          LINKMouseUpStrokeColor : opts.LINKMouseUpStrokeColor,
          LINKMouseUpStrokeWidth : opts.LINKMouseUpStrokeWidth,
          LINKMouseOverDisplay : opts.LINKMouseOverDisplay,
          LINKMouseOverOpacity : opts.LINKMouseOverOpacity,
          LINKMouseOverStrokeColor : opts.LINKMouseOverStrokeColor,
          LINKMouseOverStrokeWidth : opts.LINKMouseOverStrokeWidth,
          LINKMouseOverTooltipsSetting : opts.LINKMouseOverTooltipsSetting,
          LINKMouseOverTooltipsHtml : opts.LINKMouseOverTooltipsHtml,
          LINKMouseOverTooltipsPosition : opts.LINKMouseOverTooltipsPosition,
          LINKMouseOverTooltipsBackgroundColor : opts.LINKMouseOverTooltipsBackgroundColor,
          LINKMouseOverTooltipsBorderStyle : opts.LINKMouseOverTooltipsBorderStyle,
          LINKMouseOverTooltipsBorderWidth : opts.LINKMouseOverTooltipsBorderWidth,
          LINKMouseOverTooltipsPadding : opts.LINKMouseOverTooltipsPadding,
          LINKMouseOverTooltipsBorderRadius : opts.LINKMouseOverTooltipsBorderRadius,
          LINKMouseOverTooltipsOpacity : opts.LINKMouseOverTooltipsOpacity,
          LINKLabelDragEvent : opts.LINKLabelDragEvent,
          CHORDMouseEvent : opts.CHORDMouseEvent,
          CHORDMouseFillColorExcluded : opts.CHORDMouseFillColorExcluded,
          CHORDMouseClickDisplay : opts.CHORDMouseClickDisplay,
          CHORDMouseClickOpacity : opts.CHORDMouseClickOpacity,
          CHORDMouseClickStrokeColor : opts.CHORDMouseClickStrokeColor,
          CHORDMouseClickStrokeWidth : opts.CHORDMouseClickStrokeWidth,
          CHORDMouseDownDisplay : opts.CHORDMouseDownDisplay,
          CHORDMouseDownOpacity : opts.CHORDMouseDownOpacity,
          CHORDMouseDownStrokeColor : opts.CHORDMouseDownStrokeColor,
          CHORDMouseDownStrokeWidth : opts.CHORDMouseDownStrokeWidth,
          CHORDMouseEnterDisplay : opts.CHORDMouseEnterDisplay,
          CHORDMouseEnterOpacity : opts.CHORDMouseEnterOpacity,
          CHORDMouseEnterStrokeColor : opts.CHORDMouseEnterStrokeColor,
          CHORDMouseEnterStrokeWidth : opts.CHORDMouseEnterStrokeWidth,
          CHORDMouseLeaveDisplay : opts.CHORDMouseLeaveDisplay,
          CHORDMouseLeaveOpacity : opts.CHORDMouseLeaveOpacity,
          CHORDMouseLeaveStrokeColor : opts.CHORDMouseLeaveStrokeColor,
          CHORDMouseLeaveStrokeWidth : opts.CHORDMouseLeaveStrokeWidth,
          CHORDMouseMoveDisplay : opts.CHORDMouseMoveDisplay,
          CHORDMouseMoveOpacity : opts.CHORDMouseMoveOpacity,
          CHORDMouseMoveStrokeColor : opts.CHORDMouseMoveStrokeColor,
          CHORDMouseMoveStrokeWidth : opts.CHORDMouseMoveStrokeWidth,
          CHORDMouseOutDisplay : opts.CHORDMouseOutDisplay,
          CHORDMouseOutAnimationTime : opts.CHORDMouseOutAnimationTime,
          CHORDMouseOutOpacity : opts.CHORDMouseOutOpacity,
          CHORDMouseOutStrokeColor : opts.CHORDMouseOutStrokeColor,
          CHORDMouseOutStrokeWidth : opts.CHORDMouseOutStrokeWidth,
          CHORDMouseUpDisplay : opts.CHORDMouseUpDisplay,
          CHORDMouseUpOpacity : opts.CHORDMouseUpOpacity,
          CHORDMouseUpStrokeColor : opts.CHORDMouseUpStrokeColor,
          CHORDMouseUpStrokeWidth : opts.CHORDMouseUpStrokeWidth,
          CHORDMouseOverDisplay : opts.CHORDMouseOverDisplay,
          CHORDMouseOverOpacity : opts.CHORDMouseOverOpacity,
          CHORDMouseOverStrokeColor : opts.CHORDMouseOverStrokeColor,
          CHORDMouseOverStrokeWidth : opts.CHORDMouseOverStrokeWidth,
          HISTOGRAMxlink : opts.HISTOGRAMxlink,
          HISTOGRAMMouseEvent : opts.HISTOGRAMMouseEvent,
          HISTOGRAMMouseClickDisplay : opts.HISTOGRAMMouseClickDisplay,
          HISTOGRAMMouseClickColor : opts.HISTOGRAMMouseClickColor,
          HISTOGRAMMouseClickOpacity : opts.HISTOGRAMMouseClickOpacity,
          HISTOGRAMMouseClickStrokeColor : opts.HISTOGRAMMouseClickStrokeColor,
          HISTOGRAMMouseClickStrokeWidth : opts.HISTOGRAMMouseClickStrokeWidth,
          HISTOGRAMMouseDownDisplay : opts.HISTOGRAMMouseDownDisplay,
          HISTOGRAMMouseDownColor : opts.HISTOGRAMMouseDownColor,
          HISTOGRAMMouseDownOpacity : opts.HISTOGRAMMouseDownOpacity,
          HISTOGRAMMouseDownStrokeColor : opts.HISTOGRAMMouseDownStrokeColor,
          HISTOGRAMMouseDownStrokeWidth : opts.HISTOGRAMMouseDownStrokeWidth,
          HISTOGRAMMouseEnterDisplay : opts.HISTOGRAMMouseEnterDisplay,
          HISTOGRAMMouseEnterColor : opts.HISTOGRAMMouseEnterColor,
          HISTOGRAMMouseEnterOpacity : opts.HISTOGRAMMouseEnterOpacity,
          HISTOGRAMMouseEnterStrokeColor : opts.HISTOGRAMMouseEnterStrokeColor,
          HISTOGRAMMouseEnterStrokeWidth : opts.HISTOGRAMMouseEnterStrokeWidth,
          HISTOGRAMMouseLeaveDisplay : opts.HISTOGRAMMouseLeaveDisplay,
          HISTOGRAMMouseLeaveColor : opts.HISTOGRAMMouseLeaveColor,
          HISTOGRAMMouseLeaveOpacity : opts.HISTOGRAMMouseLeaveOpacity,
          HISTOGRAMMouseLeaveStrokeColor : opts.HISTOGRAMMouseLeaveStrokeColor,
          HISTOGRAMMouseLeaveStrokeWidth : opts.HISTOGRAMMouseLeaveStrokeWidth,
          HISTOGRAMMouseMoveDisplay : opts.HISTOGRAMMouseMoveDisplay,
          HISTOGRAMMouseMoveColor : opts.HISTOGRAMMouseMoveColor,
          HISTOGRAMMouseMoveOpacity : opts.HISTOGRAMMouseMoveOpacity,
          HISTOGRAMMouseMoveStrokeColor : opts.HISTOGRAMMouseMoveStrokeColor,
          HISTOGRAMMouseMoveStrokeWidth : opts.HISTOGRAMMouseMoveStrokeWidth,
          HISTOGRAMMouseOutDisplay : opts.HISTOGRAMMouseOutDisplay,
          HISTOGRAMMouseOutAnimationTime : opts.HISTOGRAMMouseOutAnimationTime,
          HISTOGRAMMouseOutColor : opts.HISTOGRAMMouseOutColor,
          HISTOGRAMMouseOutOpacity : opts.HISTOGRAMMouseOutOpacity,
          HISTOGRAMMouseOutStrokeColor : opts.HISTOGRAMMouseOutStrokeColor,
          HISTOGRAMMouseOutStrokeWidth : opts.HISTOGRAMMouseOutStrokeWidth,
          HISTOGRAMMouseUpDisplay : opts.HISTOGRAMMouseUpDisplay,
          HISTOGRAMMouseUpColor : opts.HISTOGRAMMouseUpColor,
          HISTOGRAMMouseUpOpacity : opts.HISTOGRAMMouseUpOpacity,
          HISTOGRAMMouseUpStrokeColor : opts.HISTOGRAMMouseUpStrokeColor,
          HISTOGRAMMouseUpStrokeWidth : opts.HISTOGRAMMouseUpStrokeWidth,
          HISTOGRAMMouseOverDisplay : opts.HISTOGRAMMouseOverDisplay,
          HISTOGRAMMouseOverColor : opts.HISTOGRAMMouseOverColor,
          HISTOGRAMMouseOverOpacity : opts.HISTOGRAMMouseOverOpacity,
          HISTOGRAMMouseOverStrokeColor : opts.HISTOGRAMMouseOverStrokeColor,
          HISTOGRAMMouseOverStrokeWidth : opts.HISTOGRAMMouseOverStrokeWidth,
          HISTOGRAMMouseOverTooltipsSetting : opts.HISTOGRAMMouseOverTooltipsSetting,
          HISTOGRAMMouseOverTooltipsHtml : opts.HISTOGRAMMouseOverTooltipsHtml,
          HISTOGRAMMouseOverTooltipsPosition : opts.HISTOGRAMMouseOverTooltipsPosition,
          HISTOGRAMMouseOverTooltipsBackgroundColor : opts.HISTOGRAMMouseOverTooltipsBackgroundColor,
          HISTOGRAMMouseOverTooltipsBorderStyle : opts.HISTOGRAMMouseOverTooltipsBorderStyle,
          HISTOGRAMMouseOverTooltipsBorderWidth : opts.HISTOGRAMMouseOverTooltipsBorderWidth,
          HISTOGRAMMouseOverTooltipsPadding : opts.HISTOGRAMMouseOverTooltipsPadding,
          HISTOGRAMMouseOverTooltipsBorderRadius : opts.HISTOGRAMMouseOverTooltipsBorderRadius,
          HISTOGRAMMouseOverTooltipsOpacity : opts.HISTOGRAMMouseOverTooltipsOpacity,
          LINEMouseEvent : opts.LINEMouseEvent,
          LINEMouseClickDisplay : opts.LINEMouseClickDisplay,
          LINEMouseClickLineOpacity : opts.LINEMouseClickLineOpacity,
          LINEMouseClickLineStrokeColor : opts.LINEMouseClickLineStrokeColor,
          LINEMouseClickLineStrokeWidth : opts.LINEMouseClickLineStrokeWidth,
          LINEMouseDownDisplay : opts.LINEMouseDownDisplay,
          LINEMouseDownLineOpacity : opts.LINEMouseDownLineOpacity,
          LINEMouseDownLineStrokeColor : opts.LINEMouseDownLineStrokeColor,
          LINEMouseDownLineStrokeWidth : opts.LINEMouseDownLineStrokeWidth,
          LINEMouseEnterDisplay : opts.LINEMouseEnterDisplay,
          LINEMouseEnterLineOpacity : opts.LINEMouseEnterLineOpacity,
          LINEMouseEnterLineStrokeColor : opts.LINEMouseEnterLineStrokeColor,
          LINEMouseEnterLineStrokeWidth : opts.LINEMouseEnterLineStrokeWidth,
          LINEMouseLeaveDisplay : opts.LINEMouseLeaveDisplay,
          LINEMouseLeaveLineOpacity : opts.LINEMouseLeaveLineOpacity,
          LINEMouseLeaveLineStrokeColor : opts.LINEMouseLeaveLineStrokeColor,
          LINEMouseLeaveLineStrokeWidth : opts.LINEMouseLeaveLineStrokeWidth,
          LINEMouseMoveDisplay : opts.LINEMouseMoveDisplay,
          LINEMouseMoveLineOpacity : opts.LINEMouseMoveLineOpacity,
          LINEMouseMoveLineStrokeColor : opts.LINEMouseMoveLineStrokeColor,
          LINEMouseMoveLineStrokeWidth : opts.LINEMouseMoveLineStrokeWidth,
          LINEMouseOutDisplay : opts.LINEMouseOutDisplay,
          LINEMouseOutAnimationTime : opts.LINEMouseOutAnimationTime,
          LINEMouseOutLineOpacity : opts.LINEMouseOutLineOpacity,
          LINEMouseOutLineStrokeColor : opts.LINEMouseOutLineStrokeColor,
          LINEMouseOutLineStrokeWidth : opts.LINEMouseOutLineStrokeWidth,
          LINEMouseUpDisplay : opts.LINEMouseUpDisplay,
          LINEMouseUpLineOpacity : opts.LINEMouseUpLineOpacity,
          LINEMouseUpLineStrokeColor : opts.LINEMouseUpLineStrokeColor,
          LINEMouseUpLineStrokeWidth : opts.LINEMouseUpLineStrokeWidth,
          LINEMouseOverDisplay : opts.LINEMouseOverDisplay,
          LINEMouseOverLineOpacity : opts.LINEMouseOverLineOpacity,
          LINEMouseOverLineStrokeColor : opts.LINEMouseOverLineStrokeColor,
          LINEMouseOverLineStrokeWidth : opts.LINEMouseOverLineStrokeWidth,
          LINEMouseOverTooltipsSetting : opts.LINEMouseOverTooltipsSetting,
          LINEMouseOverTooltipsHtml : opts.LINEMouseOverTooltipsHtml,
          LINEMouseOverTooltipsPosition : opts.LINEMouseOverTooltipsPosition,
          LINEMouseOverTooltipsBackgroundColor : opts.LINEMouseOverTooltipsBackgroundColor,
          LINEMouseOverTooltipsBorderStyle : opts.LINEMouseOverTooltipsBorderStyle,
          LINEMouseOverTooltipsBorderWidth : opts.LINEMouseOverTooltipsBorderWidth,
          LINEMouseOverTooltipsPadding : opts.LINEMouseOverTooltipsPadding,
          LINEMouseOverTooltipsBorderRadius : opts.LINEMouseOverTooltipsBorderRadius,
          LINEMouseOverTooltipsOpacity : opts.LINEMouseOverTooltipsOpacity,
          WIGMouseEvent : opts.WIGMouseEvent,
          WIGMouseClickDisplay : opts.WIGMouseClickDisplay,
          WIGMouseClickLineOpacity : opts.WIGMouseClickLineOpacity,
          WIGMouseClickLineStrokeColor : opts.WIGMouseClickLineStrokeColor,
          WIGMouseClickLineStrokeWidth : opts.WIGMouseClickLineStrokeWidth,
          WIGMouseClickFillColor : opts.WIGMouseClickFillColor,
          WIGMouseDownDisplay : opts.WIGMouseDownDisplay,
          WIGMouseDownLineOpacity : opts.WIGMouseDownLineOpacity,
          WIGMouseDownLineStrokeColor : opts.WIGMouseDownLineStrokeColor,
          WIGMouseDownLineStrokeWidth : opts.WIGMouseDownLineStrokeWidth,
          WIGMouseDownFillColor : opts.WIGMouseDownFillColor,
          WIGMouseEnterDisplay : opts.WIGMouseEnterDisplay,
          WIGMouseEnterLineOpacity : opts.WIGMouseEnterLineOpacity,
          WIGMouseEnterLineStrokeColor : opts.WIGMouseEnterLineStrokeColor,
          WIGMouseEnterLineStrokeWidth : opts.WIGMouseEnterLineStrokeWidth,
          WIGMouseEnterFillColor : opts.WIGMouseEnterFillColor,
          WIGMouseLeaveDisplay : opts.WIGMouseLeaveDisplay,
          WIGMouseLeaveLineOpacity : opts.WIGMouseLeaveLineOpacity,
          WIGMouseLeaveLineStrokeColor : opts.WIGMouseLeaveLineStrokeColor,
          WIGMouseLeaveLineStrokeWidth : opts.WIGMouseLeaveLineStrokeWidth,
          WIGMouseLeaveFillColor : opts.WIGMouseLeaveFillColor,
          WIGMouseMoveDisplay : opts.WIGMouseMoveDisplay,
          WIGMouseMoveLineOpacity : opts.WIGMouseMoveLineOpacity,
          WIGMouseMoveLineStrokeColor : opts.WIGMouseMoveLineStrokeColor,
          WIGMouseMoveLineStrokeWidth : opts.WIGMouseMoveLineStrokeWidth,
          WIGMouseMoveFillColor : opts.WIGMouseMoveFillColor,
          WIGMouseOutDisplay : opts.WIGMouseOutDisplay,
          WIGMouseOutAnimationTime : opts.WIGMouseOutAnimationTime,
          WIGMouseOutLineOpacity : opts.WIGMouseOutLineOpacity,
          WIGMouseOutLineStrokeColor : opts.WIGMouseOutLineStrokeColor,
          WIGMouseOutLineStrokeWidth : opts.WIGMouseOutLineStrokeWidth,
          WIGMouseOutFillColor : opts.WIGMouseOutFillColor,
          WIGMouseUpDisplay : opts.WIGMouseUpDisplay,
          WIGMouseUpLineOpacity : opts.WIGMouseUpLineOpacity,
          WIGMouseUpLineStrokeColor : opts.WIGMouseUpLineStrokeColor,
          WIGMouseUpLineStrokeWidth : opts.WIGMouseUpLineStrokeWidth,
          WIGMouseUpFillColor : opts.WIGMouseUpFillColor,
          WIGMouseOverDisplay : opts.WIGMouseOverDisplay,
          WIGMouseOverLineOpacity : opts.WIGMouseOverLineOpacity,
          WIGMouseOverLineStrokeColor : opts.WIGMouseOverLineStrokeColor,
          WIGMouseOverLineStrokeWidth : opts.WIGMouseOverLineStrokeWidth,
          WIGMouseOverFillColor : opts.WIGMouseOverFillColor,
          WIGMouseOverTooltipsSetting : opts.WIGMouseOverTooltipsSetting,
          WIGMouseOverTooltipsHtml : opts.WIGMouseOverTooltipsHtml,
          WIGMouseOverTooltipsPosition : opts.WIGMouseOverTooltipsPosition,
          WIGMouseOverTooltipsBackgroundColor : opts.WIGMouseOverTooltipsBackgroundColor,
          WIGMouseOverTooltipsBorderStyle : opts.WIGMouseOverTooltipsBorderStyle,
          WIGMouseOverTooltipsBorderWidth : opts.WIGMouseOverTooltipsBorderWidth,
          WIGMouseOverTooltipsPadding : opts.WIGMouseOverTooltipsPadding,
          WIGMouseOverTooltipsBorderRadius : opts.WIGMouseOverTooltipsBorderRadius,
          WIGMouseOverTooltipsOpacity : opts.WIGMouseOverTooltipsOpacity,
          SCATTERxlink : opts.SCATTERxlink,
          SCATTERMouseEvent : opts.SCATTERMouseEvent,
          SCATTERMouseClickDisplay : opts.SCATTERMouseClickDisplay,
          SCATTERMouseClickColor : opts.SCATTERMouseClickColor,
          SCATTERMouseClickCircleSize : opts.SCATTERMouseClickCircleSize,
          SCATTERMouseClickCircleOpacity : opts.SCATTERMouseClickCircleOpacity,
          SCATTERMouseClickCircleStrokeColor : opts.SCATTERMouseClickCircleStrokeColor,
          SCATTERMouseClickCircleStrokeWidth : opts.SCATTERMouseClickCircleStrokeWidth,
          SCATTERMouseClickTextFromData : opts.SCATTERMouseClickTextFromData,
          SCATTERMouseClickTextOpacity : opts.SCATTERMouseClickTextOpacity,
          SCATTERMouseClickTextColor : opts.SCATTERMouseClickTextColor,
          SCATTERMouseClickTextSize : opts.SCATTERMouseClickTextSize,
          SCATTERMouseClickTextPostionX : opts.SCATTERMouseClickTextPostionX,
          SCATTERMouseClickTextPostionY : opts.SCATTERMouseClickTextPostionY,
          SCATTERMouseClickTextDrag : opts.SCATTERMouseClickTextDrag,
          SCATTERMouseDownDisplay : opts.SCATTERMouseDownDisplay,
          SCATTERMouseDownColor : opts.SCATTERMouseDownColor,
          SCATTERMouseDownCircleSize : opts.SCATTERMouseDownCircleSize,
          SCATTERMouseDownCircleOpacity : opts.SCATTERMouseDownCircleOpacity,
          SCATTERMouseDownCircleStrokeColor : opts.SCATTERMouseDownCircleStrokeColor,
          SCATTERMouseDownCircleStrokeWidth : opts.SCATTERMouseDownCircleStrokeWidth,
          SCATTERMouseEnterDisplay : opts.SCATTERMouseEnterDisplay,
          SCATTERMouseEnterColor : opts.SCATTERMouseEnterColor,
          SCATTERMouseEnterCircleSize : opts.SCATTERMouseEnterCircleSize,
          SCATTERMouseEnterCircleOpacity : opts.SCATTERMouseEnterCircleOpacity,
          SCATTERMouseEnterCircleStrokeColor : opts.SCATTERMouseEnterCircleStrokeColor,
          SCATTERMouseEnterCircleStrokeWidth : opts.SCATTERMouseEnterCircleStrokeWidth,
          SCATTERMouseLeaveDisplay : opts.SCATTERMouseLeaveDisplay,
          SCATTERMouseLeaveColor : opts.SCATTERMouseLeaveColor,
          SCATTERMouseLeaveCircleSize : opts.SCATTERMouseLeaveCircleSize,
          SCATTERMouseLeaveCircleOpacity : opts.SCATTERMouseLeaveCircleOpacity,
          SCATTERMouseLeaveCircleStrokeColor : opts.SCATTERMouseLeaveCircleStrokeColor,
          SCATTERMouseLeaveCircleStrokeWidth : opts.SCATTERMouseLeaveCircleStrokeWidth,
          SCATTERMouseMoveDisplay : opts.SCATTERMouseMoveDisplay,
          SCATTERMouseMoveColor : opts.SCATTERMouseMoveColor,
          SCATTERMouseMoveCircleSize : opts.SCATTERMouseMoveCircleSize,
          SCATTERMouseMoveCircleOpacity : opts.SCATTERMouseMoveCircleOpacity,
          SCATTERMouseMoveCircleStrokeColor : opts.SCATTERMouseMoveCircleStrokeColor,
          SCATTERMouseMoveCircleStrokeWidth : opts.SCATTERMouseMoveCircleStrokeWidth,
          SCATTERMouseOutDisplay : opts.SCATTERMouseOutDisplay,
          SCATTERMouseOutAnimationTime : opts.SCATTERMouseOutAnimationTime,
          SCATTERMouseOutColor : opts.SCATTERMouseOutColor,
          SCATTERMouseOutCircleSize : opts.SCATTERMouseOutCircleSize,
          SCATTERMouseOutCircleOpacity : opts.SCATTERMouseOutCircleOpacity,
          SCATTERMouseOutCircleStrokeColor : opts.SCATTERMouseOutCircleStrokeColor,
          SCATTERMouseOutCircleStrokeWidth : opts.SCATTERMouseOutCircleStrokeWidth,
          SCATTERMouseUpDisplay : opts.SCATTERMouseUpDisplay,
          SCATTERMouseUpColor : opts.SCATTERMouseUpColor,
          SCATTERMouseUpCircleSize : opts.SCATTERMouseUpCircleSize,
          SCATTERMouseUpCircleOpacity : opts.SCATTERMouseUpCircleOpacity,
          SCATTERMouseUpCircleStrokeColor : opts.SCATTERMouseUpCircleStrokeColor,
          SCATTERMouseUpCircleStrokeWidth : opts.SCATTERMouseUpCircleStrokeWidth,
          SCATTERMouseOverDisplay : opts.SCATTERMouseOverDisplay,
          SCATTERMouseOverColor : opts.SCATTERMouseOverColor,
          SCATTERMouseOverCircleSize : opts.SCATTERMouseOverCircleSize,
          SCATTERMouseOverCircleOpacity : opts.SCATTERMouseOverCircleOpacity,
          SCATTERMouseOverCircleStrokeColor : opts.SCATTERMouseOverCircleStrokeColor,
          SCATTERMouseOverCircleStrokeWidth : opts.SCATTERMouseOverCircleStrokeWidth,
          SCATTERMouseOverTooltipsSetting : opts.SCATTERMouseOverTooltipsSetting,
          SCATTERMouseOverTooltipsHtml : opts.SCATTERMouseOverTooltipsHtml,
          SCATTERMouseOverTooltipsPosition : opts.SCATTERMouseOverTooltipsPosition,
          SCATTERMouseOverTooltipsBackgroundColor : opts.SCATTERMouseOverTooltipsBackgroundColor,
          SCATTERMouseOverTooltipsBorderStyle : opts.SCATTERMouseOverTooltipsBorderStyle,
          SCATTERMouseOverTooltipsBorderWidth : opts.SCATTERMouseOverTooltipsBorderWidth,
          SCATTERMouseOverTooltipsPadding : opts.SCATTERMouseOverTooltipsPadding,
          SCATTERMouseOverTooltipsBorderRadius : opts.SCATTERMouseOverTooltipsBorderRadius,
          SCATTERMouseOverTooltipsOpacity : opts.SCATTERMouseOverTooltipsOpacity,
          ARCxlink : opts.ARCxlink,
          ARCMouseEvent : opts.ARCMouseEvent,
          ARCMouseClickDisplay : opts.ARCMouseClickDisplay,
          ARCMouseClickColor : opts.ARCMouseClickColor,
          ARCMouseClickArcOpacity : opts.ARCMouseClickArcOpacity,
          ARCMouseClickArcStrokeColor : opts.ARCMouseClickArcStrokeColor,
          ARCMouseClickArcStrokeWidth : opts.ARCMouseClickArcStrokeWidth,
          ARCMouseClickTextFromData : opts.ARCMouseClickTextFromData,
          ARCMouseClickTextOpacity : opts.ARCMouseClickTextOpacity,
          ARCMouseClickTextColor : opts.ARCMouseClickTextColor,
          ARCMouseClickTextSize : opts.ARCMouseClickTextSize,
          ARCMouseClickTextPostionX : opts.ARCMouseClickTextPostionX,
          ARCMouseClickTextPostionY : opts.ARCMouseClickTextPostionY,
          ARCMouseClickTextDrag : opts.ARCMouseClickTextDrag,
          ARCMouseDownDisplay : opts.ARCMouseDownDisplay,
          ARCMouseDownColor : opts.ARCMouseDownColor,
          ARCMouseDownArcOpacity : opts.ARCMouseDownArcOpacity,
          ARCMouseDownArcStrokeColor : opts.ARCMouseDownArcStrokeColor,
          ARCMouseDownArcStrokeWidth : opts.ARCMouseDownArcStrokeWidth,
          ARCMouseEnterDisplay : opts.ARCMouseEnterDisplay,
          ARCMouseEnterColor : opts.ARCMouseEnterColor,
          ARCMouseEnterArcOpacity : opts.ARCMouseEnterArcOpacity,
          ARCMouseEnterArcStrokeColor : opts.ARCMouseEnterArcStrokeColor,
          ARCMouseEnterArcStrokeWidth : opts.ARCMouseEnterArcStrokeWidth,
          ARCMouseLeaveDisplay : opts.ARCMouseLeaveDisplay,
          ARCMouseLeaveColor : opts.ARCMouseLeaveColor,
          ARCMouseLeaveArcOpacity : opts.ARCMouseLeaveArcOpacity,
          ARCMouseLeaveArcStrokeColor : opts.ARCMouseLeaveArcStrokeColor,
          ARCMouseLeaveArcStrokeWidth : opts.ARCMouseLeaveArcStrokeWidth,
          ARCMouseMoveDisplay : opts.ARCMouseMoveDisplay,
          ARCMouseMoveColor : opts.ARCMouseMoveColor,
          ARCMouseMoveArcOpacity : opts.ARCMouseMoveArcOpacity,
          ARCMouseMoveArcStrokeColor : opts.ARCMouseMoveArcStrokeColor,
          ARCMouseMoveArcStrokeWidth : opts.ARCMouseMoveArcStrokeWidth,
          ARCMouseOutDisplay : opts.ARCMouseOutDisplay,
          ARCMouseOutAnimationTime : opts.ARCMouseOutAnimationTime,
          ARCMouseOutColor : opts.ARCMouseOutColor,
          ARCMouseOutArcOpacity : opts.ARCMouseOutArcOpacity,
          ARCMouseOutArcStrokeColor : opts.ARCMouseOutArcStrokeColor,
          ARCMouseOutArcStrokeWidth : opts.ARCMouseOutArcStrokeWidth,
          ARCMouseUpDisplay : opts.ARCMouseUpDisplay,
          ARCMouseUpColor : opts.ARCMouseUpColor,
          ARCMouseUpArcOpacity : opts.ARCMouseUpArcOpacity,
          ARCMouseUpArcStrokeColor : opts.ARCMouseUpArcStrokeColor,
          ARCMouseUpArcStrokeWidth : opts.ARCMouseUpArcStrokeWidth,
          ARCMouseOverDisplay : opts.ARCMouseOverDisplay,
          ARCMouseOverColor : opts.ARCMouseOverColor,
          ARCMouseOverArcOpacity : opts.ARCMouseOverArcOpacity,
          ARCMouseOverArcStrokeColor : opts.ARCMouseOverArcStrokeColor,
          ARCMouseOverArcStrokeWidth : opts.ARCMouseOverArcStrokeWidth,
          ARCMouseOverTooltipsSetting : opts.ARCMouseOverTooltipsSetting,
          ARCMouseOverTooltipsHtml : opts.ARCMouseOverTooltipsHtml,
          ARCMouseOverTooltipsPosition : opts.ARCMouseOverTooltipsPosition,
          ARCMouseOverTooltipsBackgroundColor : opts.ARCMouseOverTooltipsBackgroundColor,
          ARCMouseOverTooltipsBorderStyle : opts.ARCMouseOverTooltipsBorderStyle,
          ARCMouseOverTooltipsBorderWidth : opts.ARCMouseOverTooltipsBorderWidth,
          ARCMouseOverTooltipsPadding : opts.ARCMouseOverTooltipsPadding,
          ARCMouseOverTooltipsBorderRadius : opts.ARCMouseOverTooltipsBorderRadius,
          ARCMouseOverTooltipsOpacity : opts.ARCMouseOverTooltipsOpacity,
          GENExlink : opts.GENExlink,
          GENEMouseEvent : opts.GENEMouseEvent,
          GENEMouseClickDisplay : opts.GENEMouseClickDisplay,
          GENEMouseClickColor : opts.GENEMouseClickColor,
          GENEMouseClickArcOpacity : opts.GENEMouseClickArcOpacity,
          GENEMouseClickArcStrokeColor : opts.GENEMouseClickArcStrokeColor,
          GENEMouseClickArcStrokeWidth : opts.GENEMouseClickArcStrokeWidth,
          GENEMouseClickTextFromData : opts.GENEMouseClickTextFromData,
          GENEMouseClickTextOpacity : opts.GENEMouseClickTextOpacity,
          GENEMouseClickTextColor : opts.GENEMouseClickTextColor,
          GENEMouseClickTextSize : opts.GENEMouseClickTextSize,
          GENEMouseClickTextPostionX : opts.GENEMouseClickTextPostionX,
          GENEMouseClickTextPostionY : opts.GENEMouseClickTextPostionY,
          GENEMouseClickTextDrag : opts.GENEMouseClickTextDrag,
          GENEMouseDownDisplay : opts.GENEMouseDownDisplay,
          GENEMouseDownColor : opts.GENEMouseDownColor,
          GENEMouseDownArcOpacity : opts.GENEMouseDownArcOpacity,
          GENEMouseDownArcStrokeColor : opts.GENEMouseDownArcStrokeColor,
          GENEMouseDownArcStrokeWidth : opts.GENEMouseDownArcStrokeWidth,
          GENEMouseEnterDisplay : opts.GENEMouseEnterDisplay,
          GENEMouseEnterColor : opts.GENEMouseEnterColor,
          GENEMouseEnterArcOpacity : opts.GENEMouseEnterArcOpacity,
          GENEMouseEnterArcStrokeColor : opts.GENEMouseEnterArcStrokeColor,
          GENEMouseEnterArcStrokeWidth : opts.GENEMouseEnterArcStrokeWidth,
          GENEMouseLeaveDisplay : opts.GENEMouseLeaveDisplay,
          GENEMouseLeaveColor : opts.GENEMouseLeaveColor,
          GENEMouseLeaveArcOpacity : opts.GENEMouseLeaveArcOpacity,
          GENEMouseLeaveArcStrokeColor : opts.GENEMouseLeaveArcStrokeColor,
          GENEMouseLeaveArcStrokeWidth : opts.GENEMouseLeaveArcStrokeWidth,
          GENEMouseMoveDisplay : opts.GENEMouseMoveDisplay,
          GENEMouseMoveColor : opts.GENEMouseMoveColor,
          GENEMouseMoveArcOpacity : opts.GENEMouseMoveArcOpacity,
          GENEMouseMoveArcStrokeColor : opts.GENEMouseMoveArcStrokeColor,
          GENEMouseMoveArcStrokeWidth : opts.GENEMouseMoveArcStrokeWidth,
          GENEMouseOutDisplay : opts.GENEMouseOutDisplay,
          GENEMouseOutAnimationTime : opts.GENEMouseOutAnimationTime,
          GENEMouseOutColor : opts.GENEMouseOutColor,
          GENEMouseOutArcOpacity : opts.GENEMouseOutArcOpacity,
          GENEMouseOutArcStrokeColor : opts.GENEMouseOutArcStrokeColor,
          GENEMouseOutArcStrokeWidth : opts.GENEMouseOutArcStrokeWidth,
          GENEMouseUpDisplay : opts.GENEMouseUpDisplay,
          GENEMouseUpColor : opts.GENEMouseUpColor,
          GENEMouseUpArcOpacity : opts.GENEMouseUpArcOpacity,
          GENEMouseUpArcStrokeColor : opts.GENEMouseUpArcStrokeColor,
          GENEMouseUpArcStrokeWidth : opts.GENEMouseUpArcStrokeWidth,
          GENEMouseOverDisplay : opts.GENEMouseOverDisplay,
          GENEMouseOverColor : opts.GENEMouseOverColor,
          GENEMouseOverArcOpacity : opts.GENEMouseOverArcOpacity,
          GENEMouseOverArcStrokeColor : opts.GENEMouseOverArcStrokeColor,
          GENEMouseOverArcStrokeWidth : opts.GENEMouseOverArcStrokeWidth,
          GENEMouseOverTooltipsSetting : opts.GENEMouseOverTooltipsSetting,
          GENEMouseOverTooltipsHtml : opts.GENEMouseOverTooltipsHtml,
          GENEMouseOverTooltipsPosition : opts.GENEMouseOverTooltipsPosition,
          GENEMouseOverTooltipsBackgroundColor : opts.GENEMouseOverTooltipsBackgroundColor,
          GENEMouseOverTooltipsBorderStyle : opts.GENEMouseOverTooltipsBorderStyle,
          GENEMouseOverTooltipsBorderWidth : opts.GENEMouseOverTooltipsBorderWidth,
          GENEMouseOverTooltipsPadding : opts.GENEMouseOverTooltipsPadding,
          GENEMouseOverTooltipsBorderRadius : opts.GENEMouseOverTooltipsBorderRadius,
          GENEMouseOverTooltipsOpacity : opts.GENEMouseOverTooltipsOpacity,
          LOLLIPOPxlink : opts.LOLLIPOPxlink,
          LOLLIPOPMouseEvent : opts.LOLLIPOPMouseEvent,
          LOLLIPOPMouseClickDisplay : opts.LOLLIPOPMouseClickDisplay,
          LOLLIPOPMouseClickColor : opts.LOLLIPOPMouseClickColor,
          LOLLIPOPMouseClickCircleSize : opts.LOLLIPOPMouseClickCircleSize,
          LOLLIPOPMouseClickCircleOpacity : opts.LOLLIPOPMouseClickCircleOpacity,
          LOLLIPOPMouseClickCircleStrokeColor : opts.LOLLIPOPMouseClickCircleStrokeColor,
          LOLLIPOPMouseClickCircleStrokeWidth : opts.LOLLIPOPMouseClickCircleStrokeWidth,
          LOLLIPOPMouseClickTextFromData : opts.LOLLIPOPMouseClickTextFromData,
          LOLLIPOPMouseClickTextOpacity : opts.LOLLIPOPMouseClickTextOpacity,
          LOLLIPOPMouseClickTextColor : opts.LOLLIPOPMouseClickTextColor,
          LOLLIPOPMouseClickTextSize : opts.LOLLIPOPMouseClickTextSize,
          LOLLIPOPMouseClickTextPostionX : opts.LOLLIPOPMouseClickTextPostionX,
          LOLLIPOPMouseClickTextPostionY : opts.LOLLIPOPMouseClickTextPostionY,
          LOLLIPOPMouseClickTextDrag : opts.LOLLIPOPMouseClickTextDrag,
          LOLLIPOPMouseDownDisplay : opts.LOLLIPOPMouseDownDisplay,
          LOLLIPOPMouseDownColor : opts.LOLLIPOPMouseDownColor,
          LOLLIPOPMouseDownCircleSize : opts.LOLLIPOPMouseDownCircleSize,
          LOLLIPOPMouseDownCircleOpacity : opts.LOLLIPOPMouseDownCircleOpacity,
          LOLLIPOPMouseDownCircleStrokeColor : opts.LOLLIPOPMouseDownCircleStrokeColor,
          LOLLIPOPMouseDownCircleStrokeWidth : opts.LOLLIPOPMouseDownCircleStrokeWidth,
          LOLLIPOPMouseEnterDisplay : opts.LOLLIPOPMouseEnterDisplay,
          LOLLIPOPMouseEnterColor : opts.LOLLIPOPMouseEnterColor,
          LOLLIPOPMouseEnterCircleSize : opts.LOLLIPOPMouseEnterCircleSize,
          LOLLIPOPMouseEnterCircleOpacity : opts.LOLLIPOPMouseEnterCircleOpacity,
          LOLLIPOPMouseEnterCircleStrokeColor : opts.LOLLIPOPMouseEnterCircleStrokeColor,
          LOLLIPOPMouseEnterCircleStrokeWidth : opts.LOLLIPOPMouseEnterCircleStrokeWidth,
          LOLLIPOPMouseLeaveDisplay : opts.LOLLIPOPMouseLeaveDisplay,
          LOLLIPOPMouseLeaveColor : opts.LOLLIPOPMouseLeaveColor,
          LOLLIPOPMouseLeaveCircleSize : opts.LOLLIPOPMouseLeaveCircleSize,
          LOLLIPOPMouseLeaveCircleOpacity : opts.LOLLIPOPMouseLeaveCircleOpacity,
          LOLLIPOPMouseLeaveCircleStrokeColor : opts.LOLLIPOPMouseLeaveCircleStrokeColor,
          LOLLIPOPMouseLeaveCircleStrokeWidth : opts.LOLLIPOPMouseLeaveCircleStrokeWidth,
          LOLLIPOPMouseMoveDisplay : opts.LOLLIPOPMouseMoveDisplay,
          LOLLIPOPMouseMoveColor : opts.LOLLIPOPMouseMoveColor,
          LOLLIPOPMouseMoveCircleSize : opts.LOLLIPOPMouseMoveCircleSize,
          LOLLIPOPMouseMoveCircleOpacity : opts.LOLLIPOPMouseMoveCircleOpacity,
          LOLLIPOPMouseMoveCircleStrokeColor : opts.LOLLIPOPMouseMoveCircleStrokeColor,
          LOLLIPOPMouseMoveCircleStrokeWidth : opts.LOLLIPOPMouseMoveCircleStrokeWidth,
          LOLLIPOPMouseOutDisplay : opts.LOLLIPOPMouseOutDisplay,
          LOLLIPOPMouseOutAnimationTime : opts.LOLLIPOPMouseOutAnimationTime,
          LOLLIPOPMouseOutColor : opts.LOLLIPOPMouseOutColor,
          LOLLIPOPMouseOutCircleSize : opts.LOLLIPOPMouseOutCircleSize,
          LOLLIPOPMouseOutCircleOpacity : opts.LOLLIPOPMouseOutCircleOpacity,
          LOLLIPOPMouseOutCircleStrokeColor : opts.LOLLIPOPMouseOutCircleStrokeColor,
          LOLLIPOPMouseOutCircleStrokeWidth : opts.LOLLIPOPMouseOutCircleStrokeWidth,
          LOLLIPOPMouseUpDisplay : opts.LOLLIPOPMouseUpDisplay,
          LOLLIPOPMouseUpColor : opts.LOLLIPOPMouseUpColor,
          LOLLIPOPMouseUpCircleSize : opts.LOLLIPOPMouseUpCircleSize,
          LOLLIPOPMouseUpCircleOpacity : opts.LOLLIPOPMouseUpCircleOpacity,
          LOLLIPOPMouseUpCircleStrokeColor : opts.LOLLIPOPMouseUpCircleStrokeColor,
          LOLLIPOPMouseUpCircleStrokeWidth : opts.LOLLIPOPMouseUpCircleStrokeWidth,
          LOLLIPOPMouseOverDisplay : opts.LOLLIPOPMouseOverDisplay,
          LOLLIPOPMouseOverColor : opts.LOLLIPOPMouseOverColor,
          LOLLIPOPMouseOverCircleSize : opts.LOLLIPOPMouseOverCircleSize,
          LOLLIPOPMouseOverCircleOpacity : opts.LOLLIPOPMouseOverCircleOpacity,
          LOLLIPOPMouseOverCircleStrokeColor : opts.LOLLIPOPMouseOverCircleStrokeColor,
          LOLLIPOPMouseOverCircleStrokeWidth : opts.LOLLIPOPMouseOverCircleStrokeWidth,
          LOLLIPOPMouseOverTooltipsSetting : opts.LOLLIPOPMouseOverTooltipsSetting,
          LOLLIPOPMouseOverTooltipsHtml : opts.LOLLIPOPMouseOverTooltipsHtml,
          LOLLIPOPMouseOverTooltipsPosition : opts.LOLLIPOPMouseOverTooltipsPosition,
          LOLLIPOPMouseOverTooltipsBackgroundColor : opts.LOLLIPOPMouseOverTooltipsBackgroundColor,
          LOLLIPOPMouseOverTooltipsBorderStyle : opts.LOLLIPOPMouseOverTooltipsBorderStyle,
          LOLLIPOPMouseOverTooltipsBorderWidth : opts.LOLLIPOPMouseOverTooltipsBorderWidth,
          LOLLIPOPMouseOverTooltipsPadding : opts.LOLLIPOPMouseOverTooltipsPadding,
          LOLLIPOPMouseOverTooltipsBorderRadius : opts.LOLLIPOPMouseOverTooltipsBorderRadius,
          LOLLIPOPMouseOverTooltipsOpacity : opts.LOLLIPOPMouseOverTooltipsOpacity,
          
          
          // Genome options
          genomeFillColor: opts.genomeFillColor,
          genomeBorder : {
            display : opts.displayGenomeBorder,
            borderColor : opts.genomeBorderColor,
            borderSize : opts.genomeBorderSize
          },
          ticks : {
            display : opts.genomeTicksDisplay,
            len : opts.genomeTicksLen,
            color : opts.genomeTicksColor,
            textSize : opts.genomeTicksTextSize,
            textColor : opts.genomeTicksTextColor,
            scale : opts.genomeTicksScale,
            realLength : opts.genomeTicksRealLength,
            offset : opts.genomeTicksOffset
          },
          genomeLabel : {
            display : opts.genomeLabelDisplay,
            textSize : opts.genomeLabelTextSize,
            textColor : opts.genomeLabelTextColor,
            dx : opts.genomeLabelDx,
            dy : opts.genomeLabelDy,
            rotation : opts.genomeLabelOrientation
          },
          TEXTModuleDragEvent : opts.TEXTModuleDragEvent
        });

        NGCircos01.draw_genome(NGCircos01.genomeLength);
        NGCircos01.draw_genome(NGCircos01.genomeLength2);

        var circosJS = new Circos({
          container: '#'+el.id,
          width: width,
          height: height
        });

        var data=[
    {source: {id: "19", start: 22186054, end: 26186054}, target: {id: "17", start: 31478117, end: 35478117}},
    {source: {id: "4", start: 74807187, end: 78807187}, target: {id: "1", start: 89852878, end: 93852878}},
    {source: {id: "12", start: 32372614, end: 36372614}, target: {id: "12", start: 125650987, end: 129650987}},
    {source: {id: "12", start: 32372616, end: 36372616}, target: {id: "2", start: 157440784, end: 161440784}},
    {source: {id: "2", start: 131012108, end: 135012108}, target: {id: "5", start: 172541752, end: 176541752}},
    {source: {id: "22", start: 19265412, end: 23265412}, target: {id: "17", start: 31478113, end: 35478113}},
    {source: {id: "1", start: 89852783, end: 93852783}, target: {id: "2", start: 131036705, end: 135036705}},
    {source: {id: "21", start: 7827203, end: 11827203}, target: {id: "17", start: 31478116, end: 35478116}},
    {source: {id: "21", start: 7826936, end: 11826936}, target: {id: "17", start: 31478113, end: 35478113}},
    {source: {id: "21", start: 7827510, end: 11827510}, target: {id: "17", start: 31478111, end: 35478111}},
    {source: {id: "1", start: -1431493, end: 2568507}, target: {id: "17", start: 31478117, end: 35478117}},
    {source: {id: "17", start: 35360418, end: 39360418}, target: {id: "17", start: 31478115, end: 35478115}},
    {source: {id: "17", start: 31478116, end: 35478116}, target: {id: "X", start: 106297810, end: 110297810}},
    {source: {id: "17", start: 31478131, end: 35478131}, target: {id: "8", start: 134786084, end: 138786084}},
    {source: {id: "17", start: 31478111, end: 35478111}, target: {id: "2", start: 86124673, end: 90124673}},
    {source: {id: "17", start: 31478116, end: 35478116}, target: {id: "1", start: 235766312, end: 239766312}},
    {source: {id: "17", start: 31478116, end: 35478116}, target: {id: "1", start: 89853039, end: 93853039}},
    {source: {id: "17", start: 31478117, end: 35478117}, target: {id: "2", start: 131012644, end: 135012644}},
    {source: {id: "17", start: 31478115, end: 35478115}, target: {id: "11", start: 83194786, end: 87194786}},
    {source: {id: "17", start: 31478115, end: 35478115}, target: {id: "11", start: 83194786, end: 87194786}},
    {source: {id: "17", start: 31478117, end: 35478117}, target: {id: "21", start: 33677489, end: 37677489}},
    {source: {id: "17", start: 31478117, end: 35478117}, target: {id: "1", start: 89852849, end: 93852849}},
    {source: {id: "17", start: 31478114, end: 35478114}, target: {id: "X", start: 106297713, end: 110297713}}
    ]

        circosJS.layout(
            objToArray2(opts.genome,opts.genomeFillColor),

          {
            innerRadius: opts.innerRadius,
            outerRadius: opts.outerRadius,
            labels: {
              display: false,
            },
            ticks: {
              display: false
            },
            events: { },
            gap:opts.chrPad,
            cornerRadius:0,

          }
        );

        

        for (var i=0;i<opts.moduleList_circosJS.length;i++)
        { 
            data=opts.moduleList_circosJS[i][1].map(function (d) {
            return {
              source: {
                id: d.source_chr,
                start: d.source_start,
                end: d.source_end
              },
              target: {
                id: d.target_chr,
                start: d.target_start,
                end: d.target_end
              }
            }
          })
            circosJS.chords(
              opts.moduleList_circosJS[i][0],
              data,
              opts.moduleList_circosJS[i][2]

            );
        }
        
        circosJS.render();
      },

      resize: function(width, height) {

        // code to re-render the widget with a new size

      }

    };
  }
});